/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoardRouteRouteImport } from './routes/board/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardIndexRouteImport } from './routes/board/index'
import { Route as BoardSetupRouteImport } from './routes/board/setup'

const BoardRouteRoute = BoardRouteRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardRouteRoute,
} as any)
const BoardSetupRoute = BoardSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => BoardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteRouteWithChildren
  '/board/setup': typeof BoardSetupRoute
  '/board/': typeof BoardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board/setup': typeof BoardSetupRoute
  '/board': typeof BoardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRouteRouteWithChildren
  '/board/setup': typeof BoardSetupRoute
  '/board/': typeof BoardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board' | '/board/setup' | '/board/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board/setup' | '/board'
  id: '__root__' | '/' | '/board' | '/board/setup' | '/board/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRouteRoute: typeof BoardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/'
      fullPath: '/board/'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof BoardRouteRoute
    }
    '/board/setup': {
      id: '/board/setup'
      path: '/setup'
      fullPath: '/board/setup'
      preLoaderRoute: typeof BoardSetupRouteImport
      parentRoute: typeof BoardRouteRoute
    }
  }
}

interface BoardRouteRouteChildren {
  BoardSetupRoute: typeof BoardSetupRoute
  BoardIndexRoute: typeof BoardIndexRoute
}

const BoardRouteRouteChildren: BoardRouteRouteChildren = {
  BoardSetupRoute: BoardSetupRoute,
  BoardIndexRoute: BoardIndexRoute,
}

const BoardRouteRouteWithChildren = BoardRouteRoute._addFileChildren(
  BoardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRouteRoute: BoardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
