/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BRouteRouteImport } from './routes/b/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BIndexRouteImport } from './routes/b/index'
import { Route as BSetupRouteImport } from './routes/b/setup'
import { Route as BBoardSlugRouteImport } from './routes/b/$boardSlug'

const BRouteRoute = BRouteRouteImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BIndexRoute = BIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BRouteRoute,
} as any)
const BSetupRoute = BSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => BRouteRoute,
} as any)
const BBoardSlugRoute = BBoardSlugRouteImport.update({
  id: '/$boardSlug',
  path: '/$boardSlug',
  getParentRoute: () => BRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b': typeof BRouteRouteWithChildren
  '/b/$boardSlug': typeof BBoardSlugRoute
  '/b/setup': typeof BSetupRoute
  '/b/': typeof BIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b/$boardSlug': typeof BBoardSlugRoute
  '/b/setup': typeof BSetupRoute
  '/b': typeof BIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/b': typeof BRouteRouteWithChildren
  '/b/$boardSlug': typeof BBoardSlugRoute
  '/b/setup': typeof BSetupRoute
  '/b/': typeof BIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/b' | '/b/$boardSlug' | '/b/setup' | '/b/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/b/$boardSlug' | '/b/setup' | '/b'
  id: '__root__' | '/' | '/b' | '/b/$boardSlug' | '/b/setup' | '/b/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BRouteRoute: typeof BRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/b': {
      id: '/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof BRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/': {
      id: '/b/'
      path: '/'
      fullPath: '/b/'
      preLoaderRoute: typeof BIndexRouteImport
      parentRoute: typeof BRouteRoute
    }
    '/b/setup': {
      id: '/b/setup'
      path: '/setup'
      fullPath: '/b/setup'
      preLoaderRoute: typeof BSetupRouteImport
      parentRoute: typeof BRouteRoute
    }
    '/b/$boardSlug': {
      id: '/b/$boardSlug'
      path: '/$boardSlug'
      fullPath: '/b/$boardSlug'
      preLoaderRoute: typeof BBoardSlugRouteImport
      parentRoute: typeof BRouteRoute
    }
  }
}

interface BRouteRouteChildren {
  BBoardSlugRoute: typeof BBoardSlugRoute
  BSetupRoute: typeof BSetupRoute
  BIndexRoute: typeof BIndexRoute
}

const BRouteRouteChildren: BRouteRouteChildren = {
  BBoardSlugRoute: BBoardSlugRoute,
  BSetupRoute: BSetupRoute,
  BIndexRoute: BIndexRoute,
}

const BRouteRouteWithChildren =
  BRouteRoute._addFileChildren(BRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BRouteRoute: BRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
